import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notice from "@/Components/Nav/Notice";
// import MainLogo from "@/Components/Nav/MainLogo";
import NavBar from "@/Components/Nav/NavBar";
// import MainLogo from "@/Components/Nav/MainLogo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Notice></Notice>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
