name: Dynamic Next Project

on:
  push:
    branches:
      - develop

jobs:
  deploy_front:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Dependencies of Back
        working-directory: ./
        run: npm i

      - name: Build Back
        working-directory: ./
        run: npm run build

      - name: Copy Files to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            rm -rf /var/www/front
            mkdir /var/www/front'
          rsync -avz -e "ssh" ./.next ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/front
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
          echo "nvm.sh not found"
          exit 1
          }

          nvm use --lts
          cd /var/www/front
          npm i --production'

      - name: Start Server
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || {
          echo "nvm.sh not found"
          exit 1
          }

          nvm use --lts
          npm install -g pm2
          pm2 stop all
          pm2 start /var/www/front/server/app/server.js --name frontEnd'
